version: '2.3'
services:
    person_reid:
        build:
             context: ./
        container_name: person_reid
        image: person_reid:latest
        volumes:
           - type: bind
             source: ./
             target: /opt/code/

        stdin_open: true # docker run -i
        tty: true # docker run -t
        ipc: host
        network_mode: 'host'

        runtime: nvidia # for gpu
        environment:
           - NVIDIA_VISIBLE_DEVICES=all # for gpu
           - DISPLAY=$DISPLAY # for img show. run xhost + before run the container
